name: Flatpak Replicated

on:
  push:
    branches:
      - master
      - 'work/**'
  workflow_dispatch:
  pull_request:

jobs:
  flatpak:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y flatpak flatpak-builder python3 python3-yaml git curl

      - name: Initialize Flatpak Remotes
        run: |
          flatpak remote-add --if-not-exists --no-gpg-verify --user flathub https://flathub.org/repo/flathub.flatpakrepo

      - name: Clone CI Utilities
        run: git clone https://invent.kde.org/sysadmin/ci-utilities.git --depth=1

      - name: Clone CI Notary Service
        run: git clone https://invent.kde.org/sysadmin/ci-notary-service.git --depth=1

      - name: Patch flatpak-build.py for Linker Paths
        run: |
          # Fix libinih linkage by forcing library paths
          sed -i 's/"flatpak-builder",/"flatpak-builder", "--env=LD_LIBRARY_PATH=\/app\/lib:\/app\/lib64",/' ci-utilities/flatpak-build.py


      - name: Build Flatpak
        env:
          KDE_FLATPAK_MODULE_NAME: okular
        run: |
           python3 -u ci-utilities/flatpak-build.py $KDE_FLATPAK_MODULE_NAME

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: flatpak-artifacts
          path: |
            *.flatpak
            *.log
